database:
  addr: 127.0.0.1
  port: 3306
  schema: autotrade
  uname: root
  pwd: your db password

binance:
  baseurl: https://api.binance.com
  uname: your user name
  pwd: your password
  api_key_private: your api key
  secret_key_private: your secret key
  api_key_public: your order api key
  secret_key_public: your order secret key

otcbtc:
  baseurl: https://bb.otcbtc.com

version: 1.0